    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="chrome=1" />
    <meta name="renderer" content="webkit" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no, maximum-scale=1.0, minimum-scale=1.0" />
    <title>Crayfish 2</title>
    <script>
      if (!window.Promise) document.write('<script src="//github.elemecdn.com/jakearchibald/es6-promise/v3.0.2/dist/es6-promise.min.js"><\/script>');
      if (!window.fetch) document.write('<script src="//github.elemecdn.com/uglifyjs!github/fetch/v0.11.0/fetch.js"><\/script>');
    </script>
    <script src="//github.elemecdn.com/YanagiEiichi/normalize.js/0.0.8/normalize.min.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/jinkela/1.2.1/jinkela.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/jinkela/1.2.1/directives/ref.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/jinkela/1.2.1/directives/if.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/jinkela/1.2.1/directives/on.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/jinkela/1.2.1/plugins/nesting.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!facebook/regenerator/286212/runtime.js"></script>
    <script src="//github.elemecdn.com/YanagiEiichi/uparams/1.3.0/uparams.min.js"></script>
    <script src="//github.elemecdn.com/uglifyjs!YanagiEiichi/autobind/1.0.2/autobind.js"></script>
    <script src="//github.elemecdn.com/YanagiEiichi/jinkela-datepicker/af9b4a7/datepicker.js"></script>
    <!-- build src="/dist/services.js" -->
    <script wildcard="dist/services/**/*.js"></script>
    <!-- endbuild -->
    <!-- build src="/dist/components.js" -->
    <script wildcard="dist/components/**/*.js"></script>
    <!-- endbuild -->
